### ISSUE TITLE
realdriveby vehicle_next_weapon

### ISSUE THREAD

**Issue by SAESKain** [multitheftauto/mtasa-resources#193] opened 2020-03-22 14:15 UTC
**Which resource(s) have this problem?**
realdriveby

**Describe the bug**
If you do "bind <key> vehicle_next_weapon" and press this bind while in driveby mode, it will bypass the allowed weapons check and cycle through all the players weapons regardless. Eg: Being able to driveby with a combat shotgun

**To Reproduce**
1) Have the realdriveby resource loaded.
2) Enter a vehicle as a passenger and/or driver
3) RMB to enable driveby
4) Press the bind as described above

**Expected behavior**
It should only cycle through the allowed weapons for that position in the vehicle. Eg: passenger should be able to cycle through normal weapons (except CS and other larger weapons) and driver should only be able to choose between colt, uzi etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/923242/77251970-6fa94c80-6c49-11ea-83fd-f8b5e9060bc9.png)
![image](https://user-images.githubusercontent.com/923242/77251979-7768f100-6c49-11ea-8d07-460d92791a8c.png)

**Version**
Not really important, works on any version

**Additional context**
N/A other than can be extremely abused on certain servers

**Comment by zo3n** [comment] 2020-03-26 17:33
Cannot reproduce

**Comment by PlatinMTA** [comment] 2020-03-26 17:37
I can reproduce it.

**Comment by xLuxy** [comment] 2020-05-22 11:23
Cannot reproduce this. How exactly did you guys bound your key? I used `bind h vehicle_next_weapon` without success.

**Comment by xLuxy** [comment] 2020-05-22 11:26
I can only switch to an M4 while being in a vehicle as passenger, is that what you're talking about?

**Comment by PlatinMTA** [comment] 2020-05-22 11:35
I should have put the version of MTA i was using. Maybe it was releated with the ped_driveby update and that could have fixed it or change it in a way.

Tried again, I can't reproduce it anymore. Pretty sure I did back when i wrote that comment tho.

**Comment by xLive** [comment] 2020-08-06 19:53
I can't reproduce it too,

You can use machine guns if you a passenger
but not shotguns

so can you post a video?
and are you sure you're not using a modified one?

**Comment by jlillis** [comment] 2020-11-10 20:55
Cannot reproduce - marking this as closed.

**Closed by jlillis** 2020-11-10 20:55 UTC

**Comment by qaisjp** [comment] 2020-11-10 20:58
Could have been magically fixed in https://github.com/multitheftauto/mtasa-blue/pull/1442
