### ISSUE TITLE
Editor-Objects not created in dimension

### ISSUE THREAD

**Issue by Str0** [multitheftauto/mtasa-resources#132] opened 2018-10-08 05:50 UTC
**Describe the bug**

Certain Map-Objects that have a dimension above zero are not created correctly in versions newer than 1.5.6-9.14640.0 

Any object with the dimension-tag greater than zero is created in dimension 0.

` <object id="object (wdpillar01_lvs) (53)" breakable="true" interior="11" collisions="true" alpha="255" model="3498" doublesided="false" scale="1" dimension="12" posX="518.53027" posY="-20.71973" posZ="948.82001" rotX="0" rotY="90" rotZ="0"></object>`

The above object is not created in dimension 12 but oddly in dimension 0.

**To reproduce**

Update to any recent version. 
Update the default resources.
Create a map with an interior above zero as well as a dimension above zero.
Checkout said map. 

**Expected behaviour**

The map-object should be created at the given location, dimension, interior. 

**Version**
1.5.6-9.14664.0

**Additional context**

**Comment by Str0** [comment] 2018-10-08 06:03
**Addition:**

The missing objects are all created however in dimension 0.
Seems that any objects with the dimension > 0 is created in dimension 0 when parsed by the editor-resource.

**Comment by qaisjp** [comment] 2018-10-08 14:46
Duplicate of https://github.com/multitheftauto/mtasa-blue/issues/640

**Closed** 2018-10-08 14:46 UTC
Labels: duplicate
