### ISSUE TITLE
Markers don't retain their dimension

### ISSUE THREAD

**Issue by Lordmau5** [multitheftauto/mtasa-resources#190] opened 2020-03-14 10:26 UTC
**Which resource(s) have this problem?**
Editor

**Describe the bug**
When setting a dimension for a marker, then saving and reloading, it is set to 0 again.

**To Reproduce**
1. Create a marker
2. Set it's dimension to something that isn't 0
3. Save the map
4. Load the map
5. Notice that the dimension is set back to 0

**Expected behavior**
The marker to still be in whatever dimension I put it into

**Screenshots**
N/A

**Version**
Server: Windows 10, 1.5.7
Client: Windows 10, 1.5.7

**Additional context**
Opening a map that already has a marker set to another dimension will have it be loaded into that dimension.
However, trying to modify that and saving it (e.g. from 40 to 3) will not save the new value either.

**Comment by xLive** [comment] 2020-08-06 17:25
Duplicate of #142?

**Comment by jlillis** [comment] 2020-11-02 09:31
Duplicate of #142 resolved by #155

**Closed by jlillis** 2020-11-02 09:31 UTC

**Comment by qaisjp** [comment] 2020-11-02 11:50
Triggering GitHub magic comment:

**Comment by qaisjp** [comment] 2020-11-02 11:50
Duplicate of #142
