### ISSUE TITLE
Camera Stuck Mid-air after Browsing Models

### ISSUE THREAD

**Issue by Wirmaple73** [multitheftauto/mtasa-resources#298] opened 2021-03-03 13:30 UTC
**Describe the bug**

Hello, There's a bug with the Map Editor's Model Browser/Camera. sometimes when you Select an object with the Model Browser and you click on OK to place it, the Camera gets stuck Mid-air and doesn't move unless I disconnect from the Map Editor. I've reinstalled MTASA several times and tested with 1.5.7 and 1.5.8, but this still sometimes happens.

**To reproduce**

Steps to reproduce the behaviour:
1. Open the Map Editor
2. Browse for any Object and place it
3. Keep placing until Camera gets stuck.
4. Camera got stuck and you can't move it until you Disconnect from the Map Editor.

**Expected behaviour**

Model Browser should place objects, not Making the Camera stuck.

**Screenshots**

Video: https://i.imgur.com/J9CLYea.mp4

**Version**

Tested on 1.5.7 and 1.5.8
Windows 7 SP1 (No Wine or anything)

**Additional context**

If there are any solutions, please tell me. Thank you

**Comment by iDannz-Breno** [comment] 2021-03-03 16:41
cant reproduce

**Comment by xLive** [comment] 2021-03-03 21:16
I couldn't reproduce it too,
can you upload a video?

**Comment by Wirmaple73** [comment] 2021-03-04 04:32
> cant reproduce

Hi, so why am I getting this Problem even though I reinstalled MTA SA several times? any solutions please?
this is really annoying

**Comment by Dutchman101** [comment] 2021-03-04 05:02
> any solutions please? this is really annoying

Please test the fix from PR #299 by opening your `C:\Program Files (x86)\MTA San Andreas 1.5\server\mods\deathmatch\resources\[editor]\editor_gui\client` > buttonclicked.lua and replacing the contents with the patched version: [buttonclicked.lua @ PR #299](https://raw.githubusercontent.com/multitheftauto/mtasa-resources/957c82ecff00cc23e41201592c1afff924b726bd/%5Beditor%5D/editor_gui/client/buttonclicked.lua)

Let us know if that solves it @Wirmaple73

**Comment by Wirmaple73** [comment] 2021-03-04 07:44
> 
> 
> > any solutions please? this is really annoying
> 
> Please test the fix from PR #299 by opening your `C:\Program Files (x86)\MTA San Andreas 1.5\server\mods\deathmatch\resources\[editor]\editor_gui\client` > buttonclicked.lua and replacing the contents with the patched version: [buttonclicked.lua @ PR #299](https://raw.githubusercontent.com/multitheftauto/mtasa-resources/957c82ecff00cc23e41201592c1afff924b726bd/%5Beditor%5D/editor_gui/client/buttonclicked.lua)
> 
> Let us know if that solves it @Wirmaple73

omg thank you so much @Dutchman101 and @andr0xy!
I placed hundreds of Objects after replacing that LUA script and the Camera is still working perfectly, Thanks again :)

The Developers should replace the broken LUA with the Patched one

**Comment by Dutchman101** [comment] 2021-03-04 07:49
> The Developers should replace the broken LUA with the Patched one

Thanks for verifying the fix, we will do that as soon said PR gets reviewed.. after which we will close this issue.

**Closed** 2021-04-06 00:45 UTC
Labels: bug, resource:editor
