### ISSUE TITLE
Vehicles.IDE for MTA

### ISSUE THREAD

**Issue by CarlRayanitch** [multitheftauto/mtasa-resources#544] opened 2024-08-29 20:54 UTC
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a limitation in MTA (Multi Theft Auto) where we don't have the vehicles.ide functionality. This function gives much more features and possibilities to vehicles.

**Describe the solution you'd like**
I would like to add an option in the hedit tool that allows users to check or uncheck if a vehicle's wheels should behave like monster truck wheels. This would enable a 3D wheel collider for selected vehicles.

**Describe alternatives you've considered**
none.

**Additional context**
The addition of this feature would significantly improve vehicle modding in MTA by providing more flexibility and realism. Currently, the lack of vehicles.ide functionality limits the extent to which vehicle physics can be customized. By integrating this option into hedit, modders would have greater control over vehicle behavior.

**Comment by jlillis** [comment] 2024-09-04 17:07
Duplicate of #531

**Closed by jlillis** 2024-09-04 17:07 UTC
Labels: duplicate
