### ISSUE TITLE
BUGED MTA MAP EDITOR

### ISSUE THREAD

**Issue by CauanSoares** [multitheftauto/mtasa-resources#431] opened 2023-05-01 15:01 UTC
Well, I have a bug that is valid for all objects. Consist when I add the object to the map and I'm going to rotate it sideways, it rotates normally to both sides but when I set the Y rotation to 90 and I'm going to rotate it sideways, it doesn't move as it should and it bugs total. It spins all at once and sometimes it doesn't even move

**Comment by jlillis** [comment] 2023-05-01 19:36
Duplicate of #428

**Closed by jlillis** 2023-05-01 19:36 UTC
Labels: duplicate, resource:editor

**Comment by Zangomangu** [comment] 2023-07-11 19:13
This can be reopened, it's different from #428 
there's a conversion error when rotating with Y=90 or 270, i'll submit a fix
